// src/routes/preamble.svelte
<div class="preamble">
  <p class="first">
    <b>
      <a
        rel="external"
        download
        class="link"
        title="If you want Microsoft Word format"
        href="/net/Preamble3.doc"
      >
        Preamble in DOC File Format
      </a>
    </b>
  </p>
  <p>&nbsp;</p>
  <p>
    <b>
      <a rel="external" class="link" title="If you want Adobe format" href="/net/Preamble3.pdf">
        Preamble in PDF Format
      </a>
    </b>
  </p>
  <p>&nbsp;</p>
  <p>
    <b class="prompt">Take the one you want to work with.</b>
  </p>
</div>

<style lang="scss">
  .preamble {
    background-color: #ffff00;
    border-radius: 20px;
    padding: 18px;

    max-width: 1010px;
    margin: 0 auto;
    margin-top: 30px;
  }

  .link {
    font-size: x-large;
  }

  .prompt {
    color: #0000ff;
  }

  .preamble {
    p.first {
      margin-top: 0;
      padding-top: 1em;
    }
  }
</style>

// src/pages/net/preamble.tsx
import React from "react";
import Layout from "../../components/Layout";
import styles from "./preamble.module.scss";

const preamble: React.FC = () => {
  return (
    <Layout backgroundColor="#FFFF00">
      <div className={styles.preamble}>
        <p className={styles.first}>
          <b>
            <a
              className={styles.link}
              title="If you want Microsoft Word format"
              href="/net/Preamble3.doc"
            >
              Preamble in DOC File Format
            </a>
          </b>
        </p>
        <p>&nbsp;</p>
        <p>
          <b>
            <a
              className={styles.link}
              title="If you want Adobe format"
              href="/net/Preamble3.pdf"
            >
              Preamble in PDF Format
            </a>
          </b>
        </p>
        <p>&nbsp;</p>
        <p>
          <b className={styles.prompt}>Take the one you want to work with.</b>
        </p>
      </div>
    </Layout>
  );
};

export default preamble;
